DROP TABLE IF EXISTS animals CASCADE;

CREATE TABLE animals (
  id SERIAL PRIMARY KEY,
  eng VARCHAR(255) NOT NULL,
  chr VARCHAR(255) NOT NULL,
  chi VARCHAR(255) NOT NULL,
  pin VARCHAR(255) NOT NULL,
  yr INT,
  partners VARCHAR(255) NOT NULL,
  traits TEXT
)